# Generated by Django 4.1 on 2022-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="url",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
