# Generated by Django 4.1 on 2022-09-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_watch_delete_watchlist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Watch",
            new_name="Watchlist",
        ),
    ]
